services:
  api:
    # Keep your env passthroughs
    environment:
      MERCHANT_HMAC_SECRET: ${MERCHANT_HMAC_SECRET}
      DATABASE_URL: ${DATABASE_URL}

    # Quiet uvicorn access logs
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --no-access-log

    # Relax healthcheck cadence (inherits the test from base compose)
    healthcheck:
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
